title: "Hilbert's Receptionist"
author: "Angshuman Pal"
description: "I am the receptionist at Hilbert's Hotel." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

<div class="w3-content">
 <img class="mySlides" src="https://i.imgur.com/ZtdhrUA.jpg" alt="custom_html_banner1" style="width:100%">
 <img class="mySlides" src="https://i.imgur.com/ZtdhrUA.jpg" alt="custom_html_banner2" style="width:100%">
 <img class="mySlides" src="https://i.imgur.com/ZtdhrUA.jpg" alt="custom_html_banner3" style="width:100%">
 <img class="mySlides" src="https://i.imgur.com/ZtdhrUA.jpg" alt="custom_html_banner4" style="width:100%">
 <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
 <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
</div>

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "angshumanpal11@gmail.com"
#twitter_username: "twitteruser"
github_username: "angshumatic"
linkedin_username: "angshumanpal11"
#facebook_username: username
#flickr_username: username
instagram_username: "angshumatic"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: jekyll-theme-minimal

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
